version: '3.7'

services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
       - db_data:/var/lib/mysql

  wordpress:
    depends_on: 
      - db
    build: ./docker/wordpress
    ports:
      - 8080:80
    restart: always
    volumes:
      - ./web:/var/www/html
    env_file:
      - .env

volumes:
  db_data: